# Generated by Django 2.0.2 on 2018-02-19 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 12, 17, 17, 276436, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
