# Generated by Django 2.0.2 on 2018-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0003_submission_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
