# Generated by Django 2.0.2 on 2018-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0004_auto_20180219_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hash_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
